<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>OmniLauncher.Core</AssemblyName>
    <RootNamespace>OmniLauncher.Core</RootNamespace>
  </PropertyGroup>
</Project>