# -- Help ---------------------------------------------------------------------

help:
	$(info OmniLauncher - common Make targets)
	$(info )
	$(info   make build   [ROLE=frontend|backend|both])
	$(info   make start   [ROLE=frontend|backend|both] [BACKEND_MODE=local|remote] [DEBUG=1])
	$(info   make stop    [ROLE=frontend|backend|both])
	$(info   make restart [ROLE=frontend|backend|both] [BACKEND_MODE=local|remote] [DEBUG=1])
	$(info   make test    [KIND=frontend|rust|unit|backend|health|smoke|e2e|all])
	$(info   make clean   [ROLE=frontend|backend|both])
	$(info   make status)
	$(info   make logs)
	$(info )
	$(info Defaults: ROLE=both KIND=all BACKEND_MODE=local SPLIT_PORT=$(SPLIT_PORT))
	$(info Run 'make help-advanced' for compatibility aliases and variables.)
	@:

help-advanced:
	$(info OmniLauncher - advanced Make targets)
	$(info )
	$(info Compatibility aliases:)
	$(info   build-frontend build-backend)
	$(info   start-frontend start-backend start-wsl-backend)
	$(info   stop-frontend stop-backend stop-all)
	$(info   restart-frontend restart-backend restart-wsl-backend)
	$(info   prod-debug prod-debug-backend prod-debug-frontend)
	$(info   test-frontend test-rust test-unit test-backend test-health test-smoke test-e2e test-all)
	$(info   clean-frontend clean-backend remove-binary prepare-binaries)
	$(info )
	$(info Variables:)
	$(info   ROLE=frontend|backend|both       default: both)
	$(info   KIND=frontend|rust|unit|backend|health|smoke|e2e|all  default: all)
	$(info   BACKEND_MODE=local|remote        default: local)
	$(info   BACKEND_MODE=wsl                 Windows-only backend helper)
	$(info   BACKEND_URL=<url>                default: $(BACKEND_URL))
	$(info   SPLIT_HOST=<host>                default: $(SPLIT_HOST))
	$(info   SPLIT_PORT=<port>                default: $(SPLIT_PORT))
	$(info   REBUILD=1                        rebuild before start)
	$(info   CARGO_TEST_FLAGS=<flags>         default: $(CARGO_TEST_FLAGS))
	$(info   DEBUG=1 or VERBOSE=1             start binary with --debug)
	@:
